baseURL = 'https://blog.neerajajithkumar.com'
languageCode = 'en-us'
title = 'Blog - Neeraj Ajithkumar'
theme = "cactus"
[params]

  colortheme = "dark" # dark, light, white, or classic
[[menu.main]]
name = "Home"
url = "https://neerajajithkumar.com/blog"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

  mainSectionTitle = "Blog"
relativeURLs = true
canonifyURLs = true